### ISSUE TITLE
gdown.pl: command not found

### ISSUE THREAD

**Issue by minhson-kaist** [jzbjyb/oie_rank#1]
`# download model
gdown.pl https://drive.google.com/open?id=1ykuxnIE1vkhJeq-81UPtAs6K6_h3Vcw3 model.tar.gz`

This line of instruction does not work.

**Comment by jzbjyb** [comment]
`gdown.pl` is a google drive file downloading tool that can be download from [here](https://github.com/circulosmeos/gdown.pl). You can also manually download those files following the links in readme.

**Comment by minhson-kaist** [comment]
Thanks for your answer. I tried to search on Google and I can do it.
